<?php
$WNIPLD = $WOIPL = $WNIP10 = $WNIPC =$RVTN = $WNIPCVD = $RDID = $RBIP = $WATAL = $WIOS = $WNIP11 =$WNIPL9 = 
$WNIPL8 = $WAV = $WAVF = $WAVCCL = $WAVCCF = $W911 = $W911A = $TFNUM = $WDIDC = $RAAEV = $RMOHCV = $RRECSV =
$RACDPV = $RACDSV = $WACMD = $WAAE = $WCCS = $WAUMP = $WICMI = $WACDP = $WACDB = $WACDS = $LNP = $LNP2 = $WLDP2 =
$WVMB = $WLDP1 = $RTFNUM = $WFL = $WEA = $WABR = $WTFP1 = $RITNLV = $RITSL = "";

if ($_SERVER["REQUEST_METHOD"] == "POST") {
	$WNIPLD = test_input($_POST["WNIPLD"]);
	$WOIPL = test_input($_POST["WOIPL"]);
	$WNIP10 = test_input($_POST["WNIP10"]);
	$WNIPC = test_input($_POST["WNIPC"]);
	$RVTN = test_input($_POST["RVTN"]);
	$WNIPCVD = test_input($_POST["WNIPCVD"]);
	$RDID = test_input($_POST["RDID"]);
	$RBIP = test_input($_POST["RBIP"]);
	$WATAL = test_input($_POST["WATAL"]);
	$WIOS = test_input($_POST["WIOS"]);
	$WNIP11 = test_input($_POST["WNIP11"]);
	$WNIPL9 = test_input($_POST["WNIPL9"]);
	$WNIPL8 = test_input($_POST["WNIPL8"]);
	$WAV= test_input($_POST["WAV"]);
	$WAVF = test_input($_POST["WAVF"]);
	$WAVCCL = test_input($_POST["WAVCCL"]);
	$WAVCCF = test_input($_POST["WAVCCF"]);
	$W911 = test_input($_POST["W911"]);
	$W911A = test_input($_POST["W911A"]);
	$TFNUM = test_input($_POST["TFNUM"]);
	$WDIDC = test_input($_POST["WDIDC"]);
	$RAAEV = test_input($_POST["RAAEV"]);
	$RMOHCV = test_input($_POST["RMOHCV"]);
	$RRECSV = test_input($_POST["RRECSV"]);
	$RACDPV= test_input($_POST["RACDPV"]);
	$RACDSV = test_input($_POST["RACDSV"]);
	$WACMD = test_input($_POST["WACMD"]);
	$WAAE = test_input($_POST["WAAE"]);
	$WCCS = test_input($_POST["WCCS"]);
	$WAUMP = test_input($_POST["WAUMP"]);
	$WICMI = test_input($_POST["WICMI"]);
	$WACDP = test_input($_POST["WACDP"]);
	$WACDB = test_input($_POST["WACDB"]);
	$WACDS = test_input($_POST["WACDS"]);
	$LNP = test_input($_POST["LNP"]);
	$LNP2 = test_input($_POST["LNP2"]);
	$WLDP2 = test_input($_POST["WLDP2"]);
	$WVMB = test_input($_POST["WVMB"]);
	$WLDP1 = test_input($_POST["WLDP1"]);
	$RTFNUM = test_input($_POST["RTFNUM"]);
	$WFL= test_input($_POST["WFL"]);
	$WEA = test_input($_POST["WEA"]);
	$WABR = test_input($_POST["WABR"]);
	$WTFP1 = test_input($_POST["WTFP1"]);
	$RITNLV = test_input($_POST["RITNLV"]);
	$RITSL = test_input($_POST["RITSL"]);
}

function test_input($data) {
	$data = trim($data);
	$data = stripslashes($data);
	$data = htmlspecialchars($data);
	return $data;
}
?>
<?php
echo $WNIPLD;
echo "<br>";
echo $WOIPL;
echo "<br>";
echo $WNIP10;
echo "<br>";
echo $WNIPC;
echo "<br>";
echo $RVTN;
echo "<br>";
echo $WNIPCVD;
echo "<br>";
echo $RDID;
echo "<br>";
echo $RBIP;
echo "<br>";
echo $WATAL;
echo "<br>";
echo $WIOS;
echo "<br>";
echo $WNIP11;
echo "<br>";
echo $WNIPL9;
echo "<br>";
echo $WNIPL8;
echo "<br>";
echo $WAV;
echo "<br>";
echo $WAVF;
echo "<br>";
echo $WAVCCL;
echo "<br>";
echo $WAVCCF;
echo "<br>";
echo $W911;
echo "<br>";
echo $W911A;
echo "<br>";
echo $TFNUM;
echo "<br>";
echo $WDIDC;
echo "<br>";
echo $RAAEV;
echo "<br>";
echo $RMOHCV;
echo "<br>";
echo $RRECSV;
echo "<br>";
echo $RMOHCV;
echo "<br>";
echo $RRECSV;
echo "<br>";
echo $RACDPV;
echo "<br>";
echo $RACDSV;
echo "<br>";
echo $WACMD;
echo "<br>";
echo $WAAE;
echo "<br>";
echo $WCCS;
echo "<br>";
echo $WAUMP;
echo "<br>";
echo $WICMI;
echo "<br>";
echo $WACDP;
echo "<br>";
echo $WACDB;
echo "<br>";
echo $WACDS;
echo "<br>";
echo $LNP;
echo "<br>";
echo $LNP2;
echo "<br>";
echo $WLDP2;
echo "<br>";
echo $WVMB;
echo "<br>";
echo $WLDP1;
echo "<br>";
echo $RTFNUM;
echo "<br>";
echo $WFL;
echo "<br>";
echo $WEA;
echo "<br>";
echo $WABR;
echo "<br>";
echo $WTFP1;
echo "<br>";
echo $RITNLV;
echo "<br>";
echo $RITSL;
echo "<br>";
?>